https://tutorials.pytorch.kr/beginner/deep_learning_60min_blitz.html

# 1. pyTorch 입문

https://www.youtube.com/watch?v=6SF_qAd99Yg&t=35s


In [ ]:
# torch와 numpy import
import torch
import numpy as np

## Torch 기본 함수

In [ ]:
# 빈 tensor 생성
torch.empty(2,3)

tensor([[-1.1306e-09,  3.0784e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  3.0784e-41]])

In [ ]:
# 1로 구성된 tensor 생성 
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# 0으로 구성된 tensor 생성
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# 0 ~ 1 사이 랜덤으로 생성된 tensor 생성
torch.rand(2,3)

tensor([[0.3397, 0.9142, 0.9022],
        [0.5788, 0.7950, 0.5155]])

In [ ]:
# python list / numpy.array로 tensor 생성
python_list = [1,2,3]
numpy_array = np.array([11,12,13])

In [ ]:
# python list로 tensor 생성
torch.tensor(python_list)
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [ ]:
# numpy.array로 tensor 생성
torch.tensor(numpy_array)

tensor([11, 12, 13])

In [ ]:
# tensor 크기 return
torch.ones(2,3).size()

torch.Size([2, 3])

In [ ]:
# type
type(torch.ones(2,3))

torch.Tensor

## Tensor 연산

In [ ]:
# tensor 연산
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.1005, 0.7773],
        [0.1334, 0.0653]])
tensor([[0.5382, 0.9938],
        [0.1500, 0.5319]])


In [ ]:
# x + y
print(x+y)
print(y.add(x))

tensor([[1.5088, 1.8779],
        [1.1781, 0.9748]])
tensor([[1.5088, 1.8779],
        [1.1781, 0.9748]])


In [ ]:
# y = y + x
y.add_(x)
print(y)

tensor([[1.5088, 1.8779],
        [1.1781, 0.9748]])


In [ ]:
# tensor indexing
x = torch.rand(5,5)
print("x:", x)
print("x[1]:", x[1])
print("x[1:3]:", x[1:3])
print("x[2,3]:", x[2,3])
print("x[1:3, 1:3]:", x[1:3, 1:3])

[]
x: tensor([[0.9640, 0.0157, 0.0820, 0.6238, 0.6180],
        [0.0670, 0.1968, 0.9708, 0.7992, 0.9885],
        [0.2747, 0.6883, 0.6016, 0.8722, 0.1049],
        [0.3081, 0.8631, 0.3808, 0.2504, 0.6330],
        [0.5798, 0.4267, 0.6299, 0.8141, 0.1436]])
x[1]: tensor([0.0670, 0.1968, 0.9708, 0.7992, 0.9885])
x[1:3]: tensor([[0.0670, 0.1968, 0.9708, 0.7992, 0.9885],
        [0.2747, 0.6883, 0.6016, 0.8722, 0.1049]])
x[2,3]: tensor(0.8722)
x[1:3, 1:3]: tensor([[0.1968, 0.9708],
        [0.6883, 0.6016]])


In [ ]:
x = torch.rand(6,6)
print(x)
print(x.view(36))
print(x.view(2,2,9))
print(x.view(4,-1))

tensor([[0.1373, 0.0193, 0.9103, 0.7383, 0.3008, 0.5922],
        [0.8427, 0.9625, 0.8138, 0.6156, 0.6798, 0.0864],
        [0.9251, 0.6501, 0.2314, 0.4746, 0.3978, 0.8747],
        [0.0065, 0.9897, 0.2084, 0.6860, 0.4150, 0.8944],
        [0.2583, 0.2301, 0.5552, 0.9853, 0.3083, 0.5980],
        [0.1236, 0.6269, 0.2017, 0.6049, 0.8739, 0.9830]])
tensor([0.1373, 0.0193, 0.9103, 0.7383, 0.3008, 0.5922, 0.8427, 0.9625, 0.8138,
        0.6156, 0.6798, 0.0864, 0.9251, 0.6501, 0.2314, 0.4746, 0.3978, 0.8747,
        0.0065, 0.9897, 0.2084, 0.6860, 0.4150, 0.8944, 0.2583, 0.2301, 0.5552,
        0.9853, 0.3083, 0.5980, 0.1236, 0.6269, 0.2017, 0.6049, 0.8739, 0.9830])
tensor([[[0.1373, 0.0193, 0.9103, 0.7383, 0.3008, 0.5922, 0.8427, 0.9625,
          0.8138],
         [0.6156, 0.6798, 0.0864, 0.9251, 0.6501, 0.2314, 0.4746, 0.3978,
          0.8747]],

        [[0.0065, 0.9897, 0.2084, 0.6860, 0.4150, 0.8944, 0.2583, 0.2301,
          0.5552],
         [0.9853, 0.3083, 0.5980, 0.1236, 0.6269,

In [ ]:
print(torch.tensor([5.]).item())
torch.ones(1).item()

5.0
tensor([1, 2, 3])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


1.0

# PyTorch 역전파

https://www.youtube.com/watch?v=_4gEHlsvSZ8

In [ ]:
import torch

In [ ]:
# requires_grad = False가 기본값이지만, 
# True로 설정할 경우 해당 변수를 미분할 수 있게됨
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
y = x + 1
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [ ]:
# z = 2 X y^2
z = 2 * y ** 2
print(z)

tensor([[8., 8.],
        [8., 8.]], grad_fn=<MulBackward0>)


- z = 2 y ^ 2 
- z = 2 (x + 1) ^ 2
- dz/dx = 4 (x + 1)
- 따라서 z.backward(gradient=torch.ones(2,2)) 하면 x.grad에 4 (x + 1) 값이 저장된다. 

In [ ]:
# z.backward(gradient=torch.ones(2,2))
# print(x.grad)
# tensor([[8., 8.],
#       [8., 8.]])

In [ ]:
z.backward(gradient=torch.ones(2,2))

In [ ]:
print(x.grad)

tensor([[8., 8.],
        [8., 8.]])


In [ ]:
# 유튜브에서는 gradient 인자로 넘겨주지 않고 평균을 구하는 방식으로 했음.
res = z.mean()
print(res)

tensor(8., grad_fn=<MeanBackward0>)


In [ ]:
# d(res)/dx_i 는?
# res = (z_1 + z_2 + z_3 + z_4)/4
# d(res)/dx = x + 1 이 된다.
res.backward()

In [ ]:
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])


# Autograd에서 미분

https://tutorials.pytorch.kr/beginner/blitz/autograd_tutorial.html

In [ ]:
import torch
a = torch.tensor([2.,3.], requires_grad = True)
b = torch.tensor([6.,4.], requires_grad = True)
print(a)

tensor([2., 3.], requires_grad=True)


In [ ]:
Q = 3 * a ** 3 - b ** 2
print(Q)

tensor([-12.,  65.], grad_fn=<SubBackward0>)


In [ ]:
# Q : 오차(error), 종속변수
# a, b : 매개변수, 독립변수
# Q = 3a^3 - b^2
# Q를 a에 대해 편미분 = 9a^2
# Q를 b에 대해 편미분 = -2b

In [ ]:
# Q가 어떤 값이 아니라 [x, y] 형태의 벡터이므로
# Q.backward()를 할 때 인자를 넘겨줘야함. (gradient=???)
# 인자로는 Q와 같은 형태의 tensor를 넘겨주면 된다.
external_grad = torch.tensor([1., 1.,])
Q.backward(gradient=external_grad)
Q.backward()

In [ ]:
# a.grad에는 dQ/da 값 (= 9a^2) 이 저장되있는 격.
# 따라서 다음 두 결과는 같다.
print(a.grad)
print(9*a**2)
print(b.grad)

tensor([36., 81.])
tensor([36., 81.], grad_fn=<MulBackward0>)
tensor([-12.,  -8.])


In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn_pandas import DataFrameMapper
from pycox.datasets import metabric
from pycox.models import LogisticHazard
# from pycox.models import PMF
# from pycox.models import DeepHitSingle
from pycox.evaluation import EvalSurv

In [ ]:
!pip install pycox

     |████████████████████████████████| 73 kB 2.1 MB/s 
     |████████████████████████████████| 65 kB 3.9 MB/s 
     |████████████████████████████████| 41 kB 761 kB/s 
     |████████████████████████████████| 357 kB 54.7 MB/s 
     |████████████████████████████████| 124 kB 57.2 MB/s 
     |████████████████████████████████| 1.9 MB 60.6 MB/s 
     |████████████████████████████████| 2.2 MB 47.9 MB/s 
